language: generic
git:
  depth: false
env:
  global:
    secure: I4yh+ppAtUdj9ZAwWEIDuUVPRlTh0ofpjDMBSzvcqfg33WoYr7xBlv0C9GTFSAN31Tm9HxpbwnyA0us7fpToaubBIb5kHLmIEnC90JxcL3arX5s2aD6ltEivFq8FexGOIFTngyDI/VO6W5deyfoz2i3Zb3wKaD7cnrfwwIHain156mrr4KcYJKdtJXx8yA/LV9IUOUVL0SgOYKhemX8Hy9AKSgJctsWbiZB2yb+LR9re3hP9TPI6V8lzsKvgeLKqDxUgCfASxYf3ZxbGLg6ThPmSDmi4oS5MNxANFuj2ygBk4crWzposw0r6yvYxtKzUMhAGyNoSlDS3rEM1lTJ8xdM9Yoods++tRvnnBzBmYV7jDgkv1TQXp+O7W+lrvaz2ZUmseFyrk770hYZbpixalL3mCcWeN1YfgIuE3Jg6qL8wsyEZI1L8EJjZ8zH2J4888txv/4DvQWUdOl6S4Zka+UlwX1w6NMJb/s3O5Bbsy+RvpblW0meTz4n4CNJfvlWfXPp9hBay0WBZh/Mr5+QRQEyZmJuU48Mof6tBt47DyTyn5RRn51y2ZHPBib6LtUljx874LnO59CxV159FiyMPNbTkdsYi2NYLPdo3a0M/R7CSbqPDddJYsNv7TcZYuBv11xxx41iYbFZPviykTuLbpZAvLAFj9I/d0VY/nlHLb08=
matrix:
  include:
  - name: Conda Python with .yml-file
    install:
    - sudo apt-get update && sudo apt-get install -y wget
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O
      miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda env create environment.yml
    - conda activate data_pipeline_api
    script:
    - pytest --cov=data_pipeline_api || travis_terminate 1
    - conda install setuptools_scm pkginfo conda-build anaconda-client twine
    - python setup.py bdist_wheel
    - python setup.py sdist
    - scripts/release.sh
    after_success:
    - coverage xml
    - bash <(curl -s https://codecov.io/bash)
