# Large example config of different targets

reference:  # references for lookup, will not be posted, only table keys need to be specified here
  - &responsible_person
    target: 'users'
    data:
      username: '' # github username of the responsible person for use in references

  - &superseded_source
    target: 'source'
    data:
      name: ''

  - &superseded_source_version
    target: 'source_version'
    data:
      source: *superseded_source
      version_identifier: ''

patch: # list of values that will be patched
  -
    target: 'storage_type'
    data:
    name: ''
    description: ''


post:  # list of values that will be posted if missing, can be used as references, will be posted sequentially
  - &storage_type
    target: 'storage_type'
    data:
      name:  ''          # name of the storage type, e.g. ftp, https
      description: ''   # free text description of the storage type, only used if this is a new storage type

  - &storage_root
    target: 'storage_root'
    data:
      name:  ''          # name of the storage root, e.g. 'Boydorr'
      description: ''   # free text description of the storage root, only used if this is a new storage root, e.g. 'Boydorr FTP server'
      uri: ''           # link to the root of the storage, e.g. 'ftp://srv/ftp/scrc'
      type: *storage_type

  - &storage_location
    target: 'storage_location'
    data:
      name: ''              # name of the data_store, e.g. 'Model File'
      description: ''       # free text description of the data store, e.g. 'Storage on Boydorr FTP for SCRC model'
      path: ''              # path to the data from the root of the store, e.g. 'models/my_model.txt'
      hash: ''              # SHA1 hash of the file
      local_cache_url: ''   # reference to a local store of the data
      responsible_person: *responsible_person
      store_root: *storage_root

  - &accessibility
    target: 'accessibility'
    data:
      name: ''
      description: ''
      access_info: ''

  - &source_type
    target: 'source_type'
    data:
      name: ''          # name of the source_type, e.g. journal
      description: ''   # free text description of the source_type

  - &source
    target: 'source'
    data:
      name: ''          # name of the source
      description: ''   # free text description of the source
      responsible_person: *responsible_person
      source_type: *source_type
      store: *storage_location

  - &source_version
    target: 'source_version'
    data:
      version_identifier: ''  # version identifier of the source_version, e.g. 1
      description: ''         # free text description of the source_version
      accessibility: *accessibility
      responsible_person: *responsible_person
      source: *source
      store: *storage_location
      supersedes: ''          # could be a reference to *superseded_source_version

  - &processing_script
    target: 'processing_script'
    data:
      name: ''  # name of the processing_script
      responsible_person: *responsible_person
      store: *storage_location
      versions: []

  - &processing_script_version
    target: 'processing_script_version'
    data:
      version_identifier: ''  # version identifier of the processing_script_version, e.g. 1
      responsible_person: *responsible_person
      supersedes: ''          # could be a reference to a *superseded_data_product_version
      processing_script: *processing_script
      store: *storage_location
      accessibility: *accessibility
      data_product_versions: []

  - &model
    target: 'model'
    data:
      name: ''        # name of the model
      description: '' # free text description of the model
      responsible_person: *responsible_person
      store: *storage_location

  - &model_version
    target: 'model_version'
    data:
      version_identifier: ''  # version identifier of the model_version, e.g. 1
      description: ''  # free text description of the model_version
      responsible_person: *responsible_person
      supersedes: ''   # could be a reference to a *superseded_model_version
      model: *model
      store: *storage_location
      accessibility: *accessibility

  - &data_product_type
    target: 'data_product_type'
    data:
      name: ''          # name of the data_product_type
      description: ''   # free text description of the data_product_type

  - &data_product
    target: 'data_product'
    data:
      name: ''          # name of the data_product
      description: ''  # free text description of the data_product_type
      responsible_person: *responsible_person
      type: *data_product_type
      versions: []

  - &data_product_version
    target: 'data_product_version'
    data:
      version_identifier: ''   # version identifier of the data_product_version, e.g. 1
      description: ''          # free text description of the source_version
      responsible_person: *responsible_person
      supersedes: ''        # could be a reference to a *superseded_data_product_version
      data_product: *data_product
      store: *storage_location
      accessibility: *accessibility
      processing_script_version: *processing_script_version
      source_versions: []
      components: []
      model_runs: []

  - &data_product_version_component
    target: 'data_product_version_component'
    data:
      name: ''  # name of the data_product_version_component
      responsible_person: *responsible_person
      data_product_version: *data_product_version
      model_runs: []

  - &model_run
    target: 'model_run'
    data:
      release_date: ''
      description: ''
      model_config: ''
      submission_script: ''
      responsible_person: *responsible_person
      model_version: *model_version
      supersedes: ''  # could be a reference to a *superseded_model_run
      inputs: []
      outputs: []
